name: Release Build

on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Pack
        run: |
          start pack.bat
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
        with:
          file: batch-runner.exe
          draft: false
          tags: true