name: Release Build

on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Pack
        run: |
          dir
          start pack.bat
          dir
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: output.exe
          draft: false
          tags: true